-- ============================================================
-- Patch 002: Database webhook for order confirmation emails
-- Run this in Supabase Dashboard > SQL Editor (patch 006 first)
-- ============================================================
--
-- BEST PRACTICE: Send confirmation email AFTER payment is confirmed,
-- not when the order is first created (pending payment).
--
-- Primary path (recommended): Vercel /api/midtrans-notification sends
-- email via Resend when Midtrans reports settlement/capture.
--
-- Optional backup: Supabase Database Webhook on orders UPDATE:
--
-- 1. Go to Database > Webhooks
-- 2. Create or update webhook:
--    - Name: send-receipt
--    - Table: orders
--    - Events: UPDATE  (not INSERT)
--    - Type: Supabase Edge Function
--    - Edge Function: send-receipt
--    - Filter: status = confirmed (if your dashboard supports it)
--
-- Edge Function secrets (Supabase Dashboard > Edge Functions > send-receipt):
--   RESEND_API_KEY     — from resend.com (verify paperainstudio.com domain)
--   SITE_URL           — https://www.paperainstudio.com
--   FROM_EMAIL         — orders@paperainstudio.com (must match verified domain)
--
-- Vercel env vars (same values, redeploy after adding):
--   RESEND_API_KEY
--   SITE_URL
--   FROM_EMAIL
-- ============================================================
